import type {
  Paciente,
  CasoClinico,
  Sessao,
  Evolucao,
  Cobranca,
  Tarefa,
  Documento,
  Usuario,
} from "./types";

export const usuarioAtual: Usuario = {
  id: "u1",
  nome: "Dra. Isabela Mendes",
  email: "isabela@clinicapsi.com.br",
  cargo: "psicologo",
  crp: "CRP 06/12345",
  avatar: "",
};

export const pacientes: Paciente[] = [
  {
    id: "p1",
    nomeCompleto: "Ana Carolina Silva",
    dataNascimento: "1992-03-15",
    idade: 34,
    cpf: "123.456.789-00",
    telefone: "(11) 99876-5432",
    email: "ana.carolina@email.com",
    endereco: "Rua das Flores, 123 - Vila Mariana, São Paulo/SP",
    profissao: "Advogada",
    convenio: "Particular",
    responsavel: "",
    telefoneResponsavel: "",
    contatoEmergencia: "(11) 98765-4321 - Carlos Silva (marido)",
    observacoes: "Paciente pontual, boa adesão ao tratamento.",
    abordagemTerapeutica: "Terapia Cognitivo-Comportamental (TCC)",
    status: "ativo",
    tags: ["ansiedade", "TCC"],
    criadoEm: "2025-08-10",
    modalidade: "hibrido",
    plataformaOnline: "google_meet",
  },
  {
    id: "p2",
    nomeCompleto: "Pedro Henrique Oliveira",
    dataNascimento: "1985-07-22",
    idade: 40,
    cpf: "234.567.890-11",
    telefone: "(11) 99765-4321",
    email: "pedro.oliveira@email.com",
    endereco: "Av. Paulista, 456 - Bela Vista, São Paulo/SP",
    profissao: "Engenheiro Civil",
    convenio: "Unimed",
    responsavel: "",
    telefoneResponsavel: "",
    contatoEmergencia: "(11) 97654-3210 - Maria Oliveira (esposa)",
    observacoes: "Encaminhado por psiquiatra. Uso de medicação.",
    abordagemTerapeutica: "Psicodinâmica",
    status: "ativo",
    tags: ["depressão", "medicação", "psicodinâmica"],
    criadoEm: "2025-06-05",
    modalidade: "online",
    plataformaOnline: "zoom",
  },
  {
    id: "p3",
    nomeCompleto: "Mariana Costa Santos",
    dataNascimento: "1998-11-30",
    idade: 27,
    cpf: "345.678.901-22",
    telefone: "(11) 99654-3210",
    email: "mariana.costa@email.com",
    endereco: "Rua Augusta, 789 - Consolação, São Paulo/SP",
    profissao: "Designer Gráfica",
    convenio: "Particular",
    responsavel: "",
    telefoneResponsavel: "",
    contatoEmergencia: "(11) 96543-2109 - Teresa Santos (mãe)",
    observacoes: "Primeira terapia. Dificuldade em se abrir.",
    abordagemTerapeutica: "Terapia Cognitivo-Comportamental (TCC)",
    status: "ativo",
    tags: ["autoestima", "relacionamentos", "TCC"],
    criadoEm: "2026-01-15",
    modalidade: "presencial",
  },
  {
    id: "p4",
    nomeCompleto: "Lucas Gabriel Ferreira",
    dataNascimento: "2010-05-18",
    idade: 15,
    cpf: "456.789.012-33",
    telefone: "(11) 99543-2109",
    email: "",
    endereco: "Rua Vergueiro, 321 - Liberdade, São Paulo/SP",
    profissao: "Estudante",
    convenio: "Bradesco Saúde",
    responsavel: "Fernanda Ferreira",
    telefoneResponsavel: "(11) 99432-1098",
    contatoEmergencia: "(11) 99432-1098 - Fernanda Ferreira (mãe)",
    observacoes: "Adolescente. Sessões com presença da mãe quando necessário.",
    abordagemTerapeutica: "Terapia Comportamental",
    status: "ativo",
    tags: ["adolescente", "TDAH", "escolar"],
    criadoEm: "2026-02-20",
    modalidade: "presencial",
  },
  {
    id: "p5",
    nomeCompleto: "Juliana Almeida Rodrigues",
    dataNascimento: "1978-09-05",
    idade: 47,
    cpf: "567.890.123-44",
    telefone: "(11) 99432-1098",
    email: "juliana.almeida@email.com",
    endereco: "Rua Oscar Freire, 654 - Jardins, São Paulo/SP",
    profissao: "Empresária",
    convenio: "Particular",
    responsavel: "",
    telefoneResponsavel: "",
    contatoEmergencia: "(11) 98321-0987 - Roberto Rodrigues (irmão)",
    observacoes: "Caso de luto. Acompanhamento cuidadoso.",
    abordagemTerapeutica: "Abordagem Existencial-Humanista",
    status: "ativo",
    tags: ["luto", "existencial"],
    criadoEm: "2026-03-01",
    modalidade: "online",
    plataformaOnline: "microsoft_teams",
  },
  {
    id: "p6",
    nomeCompleto: "Rafael Santos Lima",
    dataNascimento: "1990-12-10",
    idade: 35,
    cpf: "678.901.234-55",
    telefone: "(11) 99321-0987",
    email: "rafael.lima@email.com",
    endereco: "Rua Haddock Lobo, 987 - Cerqueira César, São Paulo/SP",
    profissao: "Professor Universitário",
    convenio: "SulAmérica",
    responsavel: "",
    telefoneResponsavel: "",
    contatoEmergencia: "(11) 97210-9876 - Cláudia Lima (mãe)",
    observacoes: "Histórico de burnout. Boa evolução no último mês.",
    abordagemTerapeutica: "Terapia Cognitivo-Comportamental (TCC)",
    status: "ativo",
    tags: ["burnout", "estresse", "TCC"],
    criadoEm: "2025-11-10",
    modalidade: "presencial",
  },
  {
    id: "p7",
    nomeCompleto: "Camila Pereira Souza",
    dataNascimento: "1995-04-25",
    idade: 31,
    cpf: "789.012.345-66",
    telefone: "(11) 99210-9876",
    email: "camila.souza@email.com",
    endereco: "Rua Pamplona, 111 - Jardim Paulista, São Paulo/SP",
    profissao: "Psicóloga (outra área)",
    convenio: "Particular",
    responsavel: "",
    telefoneResponsavel: "",
    contatoEmergencia: "(11) 96109-8765 - André Souza (marido)",
    observacoes: "Alta terapêutica concedida em março/2026.",
    abordagemTerapeutica: "Terapia Cognitivo-Comportamental (TCC)",
    status: "alta",
    tags: ["ansiedade social", "TCC"],
    criadoEm: "2025-05-20",
    modalidade: "hibrido",
    plataformaOnline: "whatsapp_video",
  },
];

export const casosClinicas: CasoClinico[] = [
  {
    id: "c1",
    pacienteId: "p1",
    abordagem: "Terapia Cognitivo-Comportamental",
    queixaPrincipal: "Crises de ansiedade frequentes, dificuldade de concentração no trabalho",
    hipoteseClinica: "Transtorno de Ansiedade Generalizada",
    cid: "F41.1",
    nivelRisco: "medio",
    objetivos: [
      "Reduzir frequência de crises de ansiedade",
      "Desenvolver estratégias de enfrentamento",
      "Melhorar qualidade do sono",
    ],
    planoTerapeutico:
      "Sessões semanais com foco em reestruturação cognitiva e técnicas de relaxamento.",
    status: "em_andamento",
    dataInicio: "2025-08-15",
    dataEncerramento: null,
  },
  {
    id: "c2",
    pacienteId: "p2",
    abordagem: "Psicodinâmica",
    queixaPrincipal: "Humor deprimido persistente, perda de interesse em atividades",
    hipoteseClinica: "Episódio Depressivo Moderado",
    cid: "F32.1",
    nivelRisco: "alto",
    objetivos: [
      "Estabilizar humor",
      "Trabalhar questões familiares de origem",
      "Reduzir isolamento social",
    ],
    planoTerapeutico: "Sessões semanais com acompanhamento psiquiátrico concomitante.",
    status: "em_andamento",
    dataInicio: "2025-06-10",
    dataEncerramento: null,
  },
  {
    id: "c3",
    pacienteId: "p3",
    abordagem: "Terapia Cognitivo-Comportamental",
    queixaPrincipal: "Baixa autoestima, dificuldade em estabelecer vínculos afetivos",
    hipoteseClinica: "Questões de autoestima e padrões relacionais disfuncionais",
    cid: "",
    nivelRisco: "baixo",
    objetivos: [
      "Fortalecer autoestima",
      "Identificar padrões relacionais",
      "Desenvolver assertividade",
    ],
    planoTerapeutico: "Sessões semanais com foco em autoconhecimento e habilidades sociais.",
    status: "em_andamento",
    dataInicio: "2026-01-20",
    dataEncerramento: null,
  },
  {
    id: "c4",
    pacienteId: "p5",
    abordagem: "Abordagem Existencial-Fenomenológica",
    queixaPrincipal: "Luto pela perda do pai, dificuldade em aceitar a finitude",
    hipoteseClinica: "Processo de luto complicado",
    cid: "Z63.4",
    nivelRisco: "medio",
    objetivos: ["Elaborar o luto", "Resignificar a relação com o pai", "Retomar projetos de vida"],
    planoTerapeutico: "Sessões semanais com espaço para narrativa e elaboração emocional.",
    status: "em_andamento",
    dataInicio: "2026-03-05",
    dataEncerramento: null,
  },
];

export const sessoes: Sessao[] = [
  // Esta semana (05/mai a 09/mai/2026)
  {
    id: "s1",
    pacienteId: "p1",
    casoId: "c1",
    data: "2026-05-04",
    horario: "08:00",
    duracao: 50,
    tipo: "presencial",
    status: "realizada",
    linkOnline: null,
    observacoes: "",
  },
  {
    id: "s2",
    pacienteId: "p2",
    casoId: "c2",
    data: "2026-05-04",
    horario: "10:00",
    duracao: 50,
    tipo: "online",
    plataformaOnline: "zoom",
    status: "realizada",
    linkOnline: "https://zoom.us/j/123456789",
    observacoes: "",
  },
  {
    id: "s3",
    pacienteId: "p3",
    casoId: "c3",
    data: "2026-05-05",
    horario: "09:00",
    duracao: 50,
    tipo: "presencial",
    status: "confirmada",
    linkOnline: null,
    observacoes: "",
  },
  {
    id: "s4",
    pacienteId: "p4",
    casoId: "",
    data: "2026-05-05",
    horario: "11:00",
    duracao: 50,
    tipo: "presencial",
    status: "confirmada",
    linkOnline: null,
    observacoes: "Sessão com a mãe presente",
  },
  {
    id: "s5",
    pacienteId: "p5",
    casoId: "c4",
    data: "2026-05-05",
    horario: "14:00",
    duracao: 50,
    tipo: "presencial",
    status: "agendada",
    linkOnline: null,
    observacoes: "",
  },
  {
    id: "s6",
    pacienteId: "p6",
    casoId: "",
    data: "2026-05-06",
    horario: "08:00",
    duracao: 50,
    tipo: "presencial",
    status: "agendada",
    linkOnline: null,
    observacoes: "",
  },
  {
    id: "s7",
    pacienteId: "p1",
    casoId: "c1",
    data: "2026-05-06",
    horario: "10:00",
    duracao: 50,
    tipo: "online",
    plataformaOnline: "google_meet",
    status: "agendada",
    linkOnline: "https://meet.google.com/jkl-mno-pqr",
    observacoes: "",
  },
  {
    id: "s8",
    pacienteId: "p2",
    casoId: "c2",
    data: "2026-05-07",
    horario: "09:00",
    duracao: 50,
    tipo: "presencial",
    status: "agendada",
    linkOnline: null,
    observacoes: "",
  },
  {
    id: "s9",
    pacienteId: "p3",
    casoId: "c3",
    data: "2026-05-07",
    horario: "11:00",
    duracao: 50,
    tipo: "online",
    plataformaOnline: "whatsapp_video",
    status: "agendada",
    linkOnline: null,
    observacoes: "",
  },
  {
    id: "s10",
    pacienteId: "p4",
    casoId: "",
    data: "2026-05-07",
    horario: "15:00",
    duracao: 50,
    tipo: "presencial",
    status: "agendada",
    linkOnline: null,
    observacoes: "",
  },
  {
    id: "s11",
    pacienteId: "p5",
    casoId: "c4",
    data: "2026-05-08",
    horario: "08:00",
    duracao: 50,
    tipo: "online",
    plataformaOnline: "microsoft_teams",
    status: "agendada",
    linkOnline: "https://teams.microsoft.com/l/meetup/123",
    observacoes: "",
  },
  {
    id: "s12",
    pacienteId: "p6",
    casoId: "",
    data: "2026-05-08",
    horario: "14:00",
    duracao: 50,
    tipo: "presencial",
    status: "agendada",
    linkOnline: null,
    observacoes: "",
  },
  // Semana passada
  {
    id: "s13",
    pacienteId: "p1",
    casoId: "c1",
    data: "2026-04-27",
    horario: "08:00",
    duracao: 50,
    tipo: "presencial",
    status: "realizada",
    linkOnline: null,
    observacoes: "",
  },
  {
    id: "s14",
    pacienteId: "p2",
    casoId: "c2",
    data: "2026-04-28",
    horario: "10:00",
    duracao: 50,
    tipo: "online",
    plataformaOnline: "zoom",
    status: "falta",
    linkOnline: null,
    observacoes: "Paciente não compareceu, sem aviso prévio",
  },
  {
    id: "s15",
    pacienteId: "p3",
    casoId: "c3",
    data: "2026-04-29",
    horario: "09:00",
    duracao: 50,
    tipo: "presencial",
    status: "realizada",
    linkOnline: null,
    observacoes: "",
  },
  {
    id: "s16",
    pacienteId: "p5",
    casoId: "c4",
    data: "2026-04-30",
    horario: "14:00",
    duracao: 50,
    tipo: "presencial",
    status: "realizada",
    linkOnline: null,
    observacoes: "",
  },
];

export const evolucoes: Evolucao[] = [
  {
    id: "e1",
    pacienteId: "p1",
    sessaoId: "s13",
    casoId: "c1",
    terapeutaId: "u1",
    data: "2026-04-27",
    queixa: "Relata aumento da ansiedade no ambiente de trabalho após promoção.",
    intervencoes:
      "Reestruturação cognitiva sobre crenças de incapacidade. Treino de respiração diafragmática.",
    observacoesClinicas:
      "Paciente demonstra boa capacidade de reflexão. Identificou pensamentos automáticos negativos com facilidade.",
    avaliacaoRisco: "Sem risco identificado.",
    encaminhamentos: "",
    planoTerapeutico: "Manter foco em técnicas de manejo de ansiedade.",
    evolucaoLivre: "Evolução positiva. Paciente começa a aplicar técnicas no dia a dia.",
    humor: "Ansiosa, mas colaborativa",
    proximosPassos: "Continuar registro de pensamentos automáticos.",
  },
  {
    id: "e2",
    pacienteId: "p3",
    sessaoId: "s15",
    casoId: "c3",
    terapeutaId: "u1",
    data: "2026-04-29",
    queixa:
      "Dificuldade em um relacionamento amoroso recente. Sensação de não ser 'boa o suficiente'.",
    intervencoes: "Exploração de esquemas cognitivos de desvalor. Técnica de seta descendente.",
    observacoesClinicas:
      "Identificadas crenças nucleares relacionadas à infância. Vínculo terapêutico fortalecido.",
    avaliacaoRisco: "Sem risco.",
    encaminhamentos: "",
    planoTerapeutico: "Aprofundar trabalho com crenças nucleares nas próximas sessões.",
    evolucaoLivre:
      "Paciente se emocionou ao falar da relação com o pai. Momento terapêutico significativo.",
    humor: "Triste, reflexiva",
    proximosPassos: "Trazer fotos de infância na próxima sessão.",
  },
  {
    id: "e3",
    pacienteId: "p5",
    sessaoId: "s16",
    casoId: "c4",
    terapeutaId: "u1",
    data: "2026-04-30",
    queixa:
      "Sonhos recorrentes com o pai falecido. Dificuldade em descartar objetos pessoais dele.",
    intervencoes: "Escuta ativa e acolhimento. Técnica de cadeira vazia para despedida simbólica.",
    observacoesClinicas:
      "Processo de luto em fase de elaboração. Paciente começa a permitir-se sentir a dor.",
    avaliacaoRisco: "Monitorar ideação — negou pensamentos suicidas.",
    encaminhamentos: "",
    planoTerapeutico: "Continuar trabalho de elaboração do luto com foco em resignificação.",
    evolucaoLivre: "Sessão intensa emocionalmente. Paciente demonstrou alívio ao final.",
    humor: "Enlutada, com momentos de serenidade",
    proximosPassos: "Escrever uma carta ao pai como tarefa terapêutica.",
  },
  {
    id: "e4",
    pacienteId: "p1",
    sessaoId: "s1",
    casoId: "c1",
    terapeutaId: "u1",
    data: "2026-05-04",
    queixa: "Relata melhora na ansiedade após aplicar técnicas de respiração no trabalho.",
    intervencoes: "Reforço positivo. Introdução de técnica de mindfulness.",
    observacoesClinicas: "Evolução consistente. Paciente relata dormir melhor.",
    avaliacaoRisco: "Sem risco.",
    encaminhamentos: "",
    planoTerapeutico: "Manter protocolo atual. Introduzir exposição gradual a situações sociais.",
    evolucaoLivre: "Boa sessão. Paciente motivada com o progresso.",
    humor: "Otimista, engajada",
    proximosPassos: "Praticar mindfulness 10 min/dia.",
  },
];

export const cobrancas: Cobranca[] = [
  {
    id: "cob1",
    pacienteId: "p1",
    sessaoId: "s13",
    valor: 250,
    status: "pago",
    metodoPagamento: "PIX",
    dataVencimento: "2026-04-27",
    dataPagamento: "2026-04-27",
    observacoes: "",
  },
  {
    id: "cob2",
    pacienteId: "p2",
    sessaoId: "s14",
    valor: 250,
    status: "atrasado",
    metodoPagamento: "Boleto",
    dataVencimento: "2026-04-28",
    dataPagamento: null,
    observacoes: "Faltou à sessão, cobrança mantida",
  },
  {
    id: "cob3",
    pacienteId: "p3",
    sessaoId: "s15",
    valor: 200,
    status: "pago",
    metodoPagamento: "PIX",
    dataVencimento: "2026-04-29",
    dataPagamento: "2026-04-29",
    observacoes: "",
  },
  {
    id: "cob4",
    pacienteId: "p5",
    sessaoId: "s16",
    valor: 300,
    status: "pago",
    metodoPagamento: "Cartão de crédito",
    dataVencimento: "2026-04-30",
    dataPagamento: "2026-04-30",
    observacoes: "",
  },
  {
    id: "cob5",
    pacienteId: "p1",
    sessaoId: "s1",
    valor: 250,
    status: "pago",
    metodoPagamento: "PIX",
    dataVencimento: "2026-05-04",
    dataPagamento: "2026-05-04",
    observacoes: "",
  },
  {
    id: "cob6",
    pacienteId: "p2",
    sessaoId: "s2",
    valor: 250,
    status: "pendente",
    metodoPagamento: "Boleto",
    dataVencimento: "2026-05-10",
    dataPagamento: null,
    observacoes: "",
  },
  {
    id: "cob7",
    pacienteId: "p3",
    sessaoId: "s3",
    valor: 200,
    status: "pendente",
    metodoPagamento: "PIX",
    dataVencimento: "2026-05-05",
    dataPagamento: null,
    observacoes: "",
  },
  {
    id: "cob8",
    pacienteId: "p4",
    sessaoId: "s4",
    valor: 180,
    status: "pendente",
    metodoPagamento: "Convênio",
    dataVencimento: "2026-05-15",
    dataPagamento: null,
    observacoes: "Via convênio Bradesco Saúde",
  },
  {
    id: "cob9",
    pacienteId: "p6",
    sessaoId: "s6",
    valor: 220,
    status: "pendente",
    metodoPagamento: "PIX",
    dataVencimento: "2026-05-06",
    dataPagamento: null,
    observacoes: "",
  },
  {
    id: "cob10",
    pacienteId: "p5",
    sessaoId: "s5",
    valor: 300,
    status: "pendente",
    metodoPagamento: "Cartão de crédito",
    dataVencimento: "2026-05-05",
    dataPagamento: null,
    observacoes: "",
  },
];

export const tarefas: Tarefa[] = [
  {
    id: "t1",
    titulo: "Enviar relatório para escola do Lucas",
    descricao: "Elaborar relatório de acompanhamento conforme solicitação da coordenação.",
    tipo: "pendencia_clinica",
    prioridade: "alta",
    dataLimite: "2026-05-06",
    responsavel: "Dra. Isabela Mendes",
    status: "pendente",
    pacienteId: "p4",
  },
  {
    id: "t2",
    titulo: "Agendar retorno de Pedro Henrique",
    descricao: "Paciente faltou à última sessão. Entrar em contato para remarcar.",
    tipo: "retorno",
    prioridade: "alta",
    dataLimite: "2026-05-05",
    responsavel: "Recepção",
    status: "pendente",
    pacienteId: "p2",
  },
  {
    id: "t3",
    titulo: "Renovar convênio Bradesco Saúde",
    descricao: "Verificar documentação necessária para renovação do credenciamento.",
    tipo: "pendencia_administrativa",
    prioridade: "media",
    dataLimite: "2026-05-15",
    responsavel: "Administração",
    status: "em_andamento",
    pacienteId: null,
  },
  {
    id: "t4",
    titulo: "Preparar devolutiva para Juliana",
    descricao: "Devolutiva do processo de avaliação psicológica iniciado em abril.",
    tipo: "pendencia_clinica",
    prioridade: "media",
    dataLimite: "2026-05-10",
    responsavel: "Dra. Isabela Mendes",
    status: "pendente",
    pacienteId: "p5",
  },
  {
    id: "t5",
    titulo: "Atualizar prontuário de Ana Carolina",
    descricao: "Incluir evolução da última sessão no prontuário digital.",
    tipo: "tarefa",
    prioridade: "baixa",
    dataLimite: "2026-05-07",
    responsavel: "Dra. Isabela Mendes",
    status: "pendente",
    pacienteId: "p1",
  },
  {
    id: "t6",
    titulo: "Solicitar renovação do CRP",
    descricao: "Prazo de renovação vence em junho. Iniciar processo.",
    tipo: "pendencia_administrativa",
    prioridade: "baixa",
    dataLimite: "2026-06-01",
    responsavel: "Dra. Isabela Mendes",
    status: "pendente",
    pacienteId: null,
  },
  {
    id: "t7",
    titulo: "Contatar supervisora sobre caso do Pedro",
    descricao: "Discutir estratégias para o caso de depressão com risco.",
    tipo: "pendencia_clinica",
    prioridade: "urgente",
    dataLimite: "2026-05-05",
    responsavel: "Dra. Isabela Mendes",
    status: "pendente",
    pacienteId: "p2",
  },
];

export const documentos: Documento[] = [
  {
    id: "d1",
    pacienteId: "p1",
    tipo: "anamnese",
    titulo: "Anamnese Inicial — Ana Carolina Silva",
    criadoEm: "2025-08-10",
    status: "finalizado",
  },
  {
    id: "d2",
    pacienteId: "p1",
    tipo: "consentimento",
    titulo: "Termo de Consentimento Livre e Esclarecido",
    criadoEm: "2025-08-10",
    status: "finalizado",
  },
  {
    id: "d3",
    pacienteId: "p2",
    tipo: "anamnese",
    titulo: "Anamnese Inicial — Pedro Henrique Oliveira",
    criadoEm: "2025-06-05",
    status: "finalizado",
  },
  {
    id: "d4",
    pacienteId: "p4",
    tipo: "relatorio",
    titulo: "Relatório Escolar — Lucas Gabriel Ferreira",
    criadoEm: "2026-04-15",
    status: "rascunho",
  },
  {
    id: "d5",
    pacienteId: "p5",
    tipo: "encaminhamento",
    titulo: "Encaminhamento Psiquiátrico — Juliana A. Rodrigues",
    criadoEm: "2026-03-20",
    status: "finalizado",
  },
  {
    id: "d6",
    pacienteId: "p3",
    tipo: "triagem",
    titulo: "Formulário de Triagem — Mariana Costa Santos",
    criadoEm: "2026-01-15",
    status: "finalizado",
  },
];

// Helper para buscar nome do paciente
export function nomePaciente(id: string): string {
  return pacientes.find((p) => p.id === id)?.nomeCompleto ?? "Desconhecido";
}
